### ISSUE TITLE
What is the point of clean_package_name?

### ISSUE THREAD

**Issue by Morganamilo** [vn971/rua#71] opened 2019-09-16 19:16 UTC
I understand makepkg has these restrictions on pkgname.

I could some what understand if this function returned an error, but instead is actually edits the depend's name.

What does this aim to solve? If the package had an invalid depend then you assume the depend will fail to match a package anyway and you end up with a clear missing package error. If the depend does match something then fine, so what?

makepkg has it's own lint system that makes invalid stuff fail to build, therefore invalid stuff should not be on the AUR. I think we should just rely on makepkg's linting instead of checking stuff for ourselves.

**Comment by vn971** [comment] 2019-09-16 19:42
hm, interesting. Well, one obvious goal is to not have versions in the package name. That's how it's used during normal operation.

Regarding the part that does assertions. I think there are certain character that, should AUR RPC ever return them, would/could break RUA. For example, the directory separator `/`, or null bytes, or maybe even a name starting with a dash. The client is obviously not written in bash, but we still do shelling, so some potential problems/traps still apply to the client.

We could only forbid a certain subset of the possible strings, but... Does it worth it? After all, one of the good principles of software engineering is to verify input whenever possible, and not blindly trust the availability/reliability of external systems.

**Comment by vn971** [comment] 2019-10-31 14:17
So to re-iterate:
> What does this aim to solve? If the package had an invalid depend then you assume the depend will fail to match a package anyway and you end up with a clear missing package error. If the depend does match something then fine, so what?

This part is there by design. I don't want to extend trust for correctness to external systems (AUR RPC), so I'd double-check package names locally as well. This is fine for me, I think it's an OK approach.

> I could some what understand if this function returned an error, but instead is actually edits the depend's name.

The only way the current code edits the name is it removes the version. This is **currently** by design as, RUA is currently unaware of versions. I'm beginning to be a bit doubtful of that, so I might change that in the future. But for now, it is how it is. If it will ever be rewritten to version-aware approach, then this code will obviously have to change, there's zero chance of accidentally missing it in the future.

Closing.

**Closed by vn971** 2019-10-31 14:17 UTC
Labels: question
