### ISSUE TITLE
panicked at 'Failed to canonicalize build dir

### ISSUE THREAD

**Issue by doums** [vn971/rua#119] opened 2020-04-16 12:15 UTC
Hi!

I just installed rua via cargo.
My Rust setup is managed by `rustup`, installed via the official script: https://sh.rustup.rs (not via the pacman package).

And for the first time I try to install an AUR package with rua ([gotop-bin](https://aur.archlinux.org/packages/gotop-bin/)), it panics:
```
$ rua install gotop-bin

Reviewing "/home/pierre/.config/rua/pkg/gotop-bin".
[S]=run shellcheck on PKGBUILD, [D]=(identical to upstream, empty diff), [T]=run shell to edit/inspect, [O]=ok, use package. o
thread 'main' panicked at 'Failed to canonicalize build dir "/home/pierre/.cache/rua/build/gotop-bin" for pkgbase gotop-bin, No such file or directory (os error 2)', /home/pierre/.cargo/registry/src/github.com-1ecc6299db9ec823/rua-0.17.6/src/action_install.rs:125:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by vn971** [comment] 2020-04-16 15:24
That's strange. Guessing by the output, this is not the first time rua is being run. It says `[D]=(identical to upstream, empty diff)`, which it prints when upstream is already reviewed, and changes merged in.

Still, it's strange. Does this problem happen for all packages? Or are some successful but some not?

**Comment by vn971** [comment] 2020-04-16 15:36
OK wait, it's a regression from the latest release. Gotta fix ASAP.

**Comment by vn971** [comment] 2020-04-16 15:41
Related: https://github.com/vn971/rua/pull/116
(Pasting not to blame, but to give context.)

**Comment by doums** [comment] 2020-04-16 15:54
> That's strange. Guessing by the output, this is not the first time rua is being run. It says `[D]=(identical to upstream, empty diff)`, which it prints when upstream is already reviewed, and changes merged in.

Yes, you are right, I pasted the output of another attempt of `rua install gotop-bin`.
But the first time, the output ended the same.

**Comment by vn971** [comment] 2020-04-16 16:00
Yes. I've already made the fix, now releasing. Thanks a lot for raising the issue!

**Comment by doums** [comment] 2020-04-16 16:02
Ok cool! Thank you for this tool :)

**Comment by vn971** [comment] 2020-04-16 16:15
Fixed in https://github.com/vn971/rua/commit/338ce2df479222864fdae02da651326555dd3359

**Closed by vn971** 2020-04-16 16:15 UTC
Labels: bug

**Comment by vn971** [comment] 2020-04-16 16:17
// I also touched other directories, even though it was not really necessary. Still, I felt it's a better contract to have all directories already exist in a RuaPaths struct.

**Comment by doums** [comment] 2020-04-16 21:44
Hi,

I'm afraid that you have not resolved the bug:
```
$ rua install polybar

In order to install all targets, the following pacman packages will need to be installed:
  python-sphinx
  libmpdclient

And the following AUR packages will need to be built and installed:
  polybar

Proceed? [O]=ok, Ctrl-C=abort. o

Reviewing "/home/pierre/.config/rua/pkg/polybar".
[D]=view upstream changes since your last review, [M]=accept/merge upstream changes, [S]=(shellcheck not available until you merge), [T]=run shell to edit/inspect, [O]=(cannot use the package until you merge) m

Reviewing "/home/pierre/.config/rua/pkg/polybar".
[S]=run shellcheck on PKGBUILD, [D]=(identical to upstream, empty diff), [T]=run shell to edit/inspect, [O]=ok, use package. o
Packages need to be installed:

    pacman -S --asdeps --needed 'libmpdclient' 'python-sphinx'

Enter S to `sudo` install it, or install manually and press M when done. S
[sudo] Mot de passe de pierre :
résolution des dépendances…
recherche des conflits entre paquets…

Paquets (14) python-babel-2.8.0-4  python-docutils-0.14-4  python-imagesize-1.2.0-1
             python-pytz-2019.3-3  python-snowballstemmer-2.0.0-3
             python-sphinx-alabaster-theme-0.7.12-3  python-sphinxcontrib-applehelp-1.0.2-1
             python-sphinxcontrib-devhelp-1.0.2-1  python-sphinxcontrib-htmlhelp-1.0.3-1
             python-sphinxcontrib-jsmath-1.0.1-4  python-sphinxcontrib-qthelp-1.0.3-1
             python-sphinxcontrib-serializinghtml-1.1.4-1  libmpdclient-2.18-1
             python-sphinx-3.0.1-1

Taille totale du téléchargement :   8,42 MiB
Taille totale installée :        49,02 MiB

:: Procéder à l’installation ? [O/n] o
:: Récupération des paquets…
 libmpdclient-2.18-1-x86_64    73,8 KiB  1678 KiB/s 00:00 [------------------------------] 100%
 python-pytz-2019.3-3-any     172,9 KiB  5,63 MiB/s 00:00 [------------------------------] 100%
 python-babel-2.8.0-4-any       5,5 MiB  36,7 MiB/s 00:00 [------------------------------] 100%
 python-docutils-0.14-4-any   663,5 KiB  64,8 MiB/s 00:00 [------------------------------] 100%
 python-imagesize-1.2.0-...     8,3 KiB  0,00   B/s 00:00 [------------------------------] 100%
 python-snowballstemmer-...   136,7 KiB  0,00   B/s 00:00 [------------------------------] 100%
 python-sphinx-alabaster...    14,7 KiB  0,00   B/s 00:00 [------------------------------] 100%
 python-sphinxcontrib-ap...    29,4 KiB  0,00   B/s 00:00 [------------------------------] 100%
 python-sphinxcontrib-de...    23,2 KiB  0,00   B/s 00:00 [------------------------------] 100%
 python-sphinxcontrib-ht...    30,9 KiB  0,00   B/s 00:00 [------------------------------] 100%
 python-sphinxcontrib-js...     8,2 KiB  0,00   B/s 00:00 [------------------------------] 100%
 python-sphinxcontrib-qt...    27,4 KiB  0,00   B/s 00:00 [------------------------------] 100%
 python-sphinxcontrib-se...    25,3 KiB  0,00   B/s 00:00 [------------------------------] 100%
 python-sphinx-3.0.1-1-any   1771,4 KiB  7,97 MiB/s 00:00 [------------------------------] 100%
(14/14) vérification des clés dans le trousseau           [------------------------------] 100%
(14/14) vérification de l’intégrité des paquets           [------------------------------] 100%
(14/14) chargement des fichiers des paquets               [------------------------------] 100%
(14/14) analyse des conflits entre fichiers               [------------------------------] 100%
(14/14) vérification de l’espace disque disponible        [------------------------------] 100%
:: Traitement des changements du paquet…
( 1/14) installation de libmpdclient                      [------------------------------] 100%
( 2/14) installation de python-pytz                       [------------------------------] 100%
( 3/14) installation de python-babel                      [------------------------------] 100%
( 4/14) installation de python-docutils                   [------------------------------] 100%
( 5/14) installation de python-imagesize                  [------------------------------] 100%
( 6/14) installation de python-snowballstemmer            [------------------------------] 100%
Dépendances optionnelles pour python-snowballstemmer
    python-pystemmer: for improved performance
( 7/14) installation de python-sphinx-alabaster-theme     [------------------------------] 100%
( 8/14) installation de python-sphinxcontrib-applehelp    [------------------------------] 100%
( 9/14) installation de python-sphinxcontrib-devhelp      [------------------------------] 100%
(10/14) installation de python-sphinxcontrib-htmlhelp     [------------------------------] 100%
(11/14) installation de python-sphinxcontrib-jsmath       [------------------------------] 100%
(12/14) installation de python-sphinxcontrib-qthelp       [------------------------------] 100%
(13/14) installation de python-sphinxcontrib-serializ...  [------------------------------] 100%
(14/14) installation de python-sphinx                     [------------------------------] 100%
Dépendances optionnelles pour python-sphinx
    imagemagick: for ext.imgconverter [installé]
    texlive-latexextra: for generation of PDF documentation
:: Exécution des crochets de post-transaction…
(1/1) Arming ConditionNeedsUpdate...
thread 'main' panicked at 'Failed to canonicalize build dir "/home/pierre/.cache/rua/build/polybar" for pkgbase polybar, No such file or directory (os error 2)', /home/pierre/.cargo/registry/src/github.com-1ecc6299db9ec823/rua-0.17.7/src/action_install.rs:125:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by vn971** [comment] 2020-04-17 07:08
Terribly sorry, I got confused with directory creation. What's worse, I had the code working in the middle of the rewrite, so the code worked at some point and local test was successful even though the final release was not.

Made the fix to canonicalization. Tested. Just released.

**Comment by vn971** [comment] 2020-04-17 07:15
What basically happens, is that `rua` wants to copy the cloned package to `~/.cache` for building. Due to the behavior of makepkg we want to use absolute paths: https://github.com/vn971/rua/pull/115#issuecomment-605525029  But we cannot canonicalize a directory before we create it. So the tool errors out just because the directory is not created yet.

**Comment by doums** [comment] 2020-04-17 13:38
Ok, I confirm, this is fixed. Thank for the explanations.
