### ISSUE TITLE
Segfaults on search

### ISSUE THREAD

**Issue by ojensen5115** [vn971/rua#202] opened 2023-02-19 06:25 UTC
I've just installed this via AUR, by performing a `makepkg` followed by `sudo pacman -U rua-0.19.3-2-x86_64.pkg.tar.zst`

Attempting to perform any search simply dumps core with a segmentation fault:

```
[ojensen@framework ~/aur/rua (master)]$ rua search mkinitcpio-firmware
Segmentation fault (core dumped)
[ojensen@framework ~/aur/rua (master)]$ rua search mkinitcpio
Segmentation fault (core dumped)
[ojensen@framework ~/aur/rua (master)]$ rua search foo
Segmentation fault (core dumped)
```

Running rua 0.19.3-2 (2ac1d1ea298df2896dd568526d6b5087c36ada5b) on Arch, compiled with the latest rust stable (1.67.1)

**Comment by morngrar** [comment] 2023-02-24 16:53
Encountering this as well, same rua version, and is a problem both on `search` and `upgrade` subcommands.

**Comment by Tobitaube** [comment] 2023-02-28 10:34
Same here

**Comment by pernu** [comment] 2023-03-04 06:01
With my 0.19.1 package I built back in Oct 2022, no issues. But when I build either 0.19.3, 0.19.2 or 0.19.1 (fresh build), all of them segfault. So it's not a change in the rua code, more likely some change on the rust build side (maybe one of the many dependencies).

**Comment by VSpike** [comment] 2023-03-04 15:48
Same for me too ... it's a shame as I don't have an older package saved to roll back to!

**Comment by NarinderS** [comment] 2023-03-04 20:51
This seems to be caused by the `prettytable-rs` dependency. Bumping the version to `0.10.0` fixes the issue: https://github.com/phsym/prettytable-rs/issues/130

**Comment by morngrar** [comment] 2023-03-06 11:48
> This seems to be caused by the `prettytable-rs` dependency. Bumping the version to `0.10.0` fixes the issue: #198

There's already an unmerged PR for this by dependabot since December #198. Should be a one-click fix

**Comment by morngrar** [comment] 2023-03-09 21:33
v0.19.4 updates the relevant dependencies, and the problem is solved for me. This issue can probably be closed :+1:

**Comment by vn971** [comment] 2023-07-31 17:29
Oh darn, I had email notifications broken and I've primarily used GitLab at work for some months :see_no_evil: 

Very sorry about this!

The issue is indeed likely solved, so closing

**Closed by vn971** 2023-07-31 17:29 UTC
